name: Decline Pull Requests
on:
  pull_request:
    branches:
      - main
      - staging
jobs:
  decline_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Decline PR
        run: |
          TOKEN="${{ secrets.GITHUB_TOKEN }}"
          API_URL="https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}"
          curl -X POST -H "Authorization: token $TOKEN" -H "Content-Type: application/json" -d '{"state":"closed", "labels":["declined"], "body":"Declined pull request on branch main."}' $API_URL